### ISSUE TITLE
RSVP event error checking

### ISSUE THREAD

**Issue by shy-duck** [sarimabbas/project-winter-sound#6]
High priority

❌ - it should allow  to RSVP
     I fill out the email input and submit the form. After the form is
     submitted I check the page for the presence of the email address and
     confirmation code. This test was not run because one of the prior
     tests failed.

❌ - it should not allow  to RSVP
     I fill out the email input and submit the form. After the form is
     submitted I check the page for the presence of the email address among
     those attending. It should not be there. Note that I am turning off
     client-side form validation so that you'll have to handle validation
     on the server! I also check for an element with class="errors". This
     should be there and it should show the user a message like "only
     Yalies!", though, the particular message doesn't matter. This test was
     not run because one of the prior tests failed.

**Comment by sarimabbas** [comment]
Completed in 08499b44fb44882cab46b082c0ac5426f0773135
